default:
    image: node
    
workflow:
  rules: 
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
stages: 
    - build
    - test
    - deploy


build:
    stage: build
    script: |
        
        echo CI_EXTERNAL_PULL_REQUEST_IID: $CI_EXTERNAL_PULL_REQUEST_IID
        echo CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY	: $CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY	
        echo CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY : $CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY
        echo CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME : $CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME
        echo CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME : $CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME
        
        git status
        git log
        git checkout $CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY
        git status
        node --version
        
