default:
    image: node
    
workflow:
  rules: 
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
    
    
stages: 
    - build
    - test
    - deploy

build:
    stage: build
    script:
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
        - node --version
        - yarn --version
        - npm --version
